---
- name: create node exporter user
  user:
    name: node_exporter
    comment: "Node Exporter service user"

- name: create folder structure
  file:
    path: "{{ item }}"
    state: directory
    owner: node_exporter
    group: node_exporter
    recurse: yes
  loop:
    - "{{ node_exporter_folder }}"
    - "{{ node_exporter_versions_folder }}"
  notify:
    - restart

- name: download node exporter binary
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: "{{ node_exporter_versions_folder }}"
    remote_src: yes
  notify:
    - restart

- name: move files into version folder
  command: "mv {{ node_exporter_versions_folder }}/node_exporter-{{ node_exporter_version }}.linux-arm64 {{ node_exporter_versions_folder }}/{{ node_exporter_version }}"
  
- name: ensure ownership
  command: "chown {{ node_exporter_user }}:{{ node_exporter_group }} -R {{ node_exporter_folder }}"

- name: template out service file
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/node_exporter.service"
  notify:
    - restart

- name: symlink downloaded version to current
  file:
    src: "{{ node_exporter_versions_folder }}/{{ node_exporter_version }}"
    dest: "{{ node_exporter_folder }}/current"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    state: link
  notify:
    - restart
  
