---
- name: create folder structure
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    recurse: yes
  loop:
    - "{{ prometheus_folder }}"
    - "{{ prometheus_config_folder }}"
    - "{{ prometheus_versions_folder }}"
    - "/var/lib/prometheus/"
    - "/etc/prometheus/consoles"
    - "/etc/prometheus/console_libraries"
  notify:
    - restart

- name: create prometheus user
  user:
    name: prometheus
    comment: "Prometheus service user"

- name: download prometheus binary
  unarchive:
    src: "{{ prometheus_download_url }}"
    dest: "{{ prometheus_versions_folder }}"
    remote_src: yes
  notify:
    - restart

- name: move files into version folder
  command: "mv {{ prometheus_versions_folder }}/prometheus-{{ prometheus_version }}.linux-arm64 {{ prometheus_versions_folder }}/{{ prometheus_version }}"
  ignore_errors: yes
  
- name: ensure ownership
  command: "chown {{ prometheus_user }}:{{ prometheus_group }} -R {{ prometheus_folder }}"

- name: ensure ownership of console folders
  file:
    path: "{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    recurse: yes
  loop:
    - "/var/lib/prometheus/"
    - "/etc/prometheus/consoles"
    - "/etc/prometheus/console_libraries"


- name: template out service file
  template:
    src: prometheus.service.j2
    dest: "/etc/systemd/system/prometheus.service"
  notify:
    - restart

- name: template out prometheus config file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_folder }}/prometheus.yml"

- name: symlink downloaded version to current
  file:
    src: "{{ prometheus_versions_folder }}/{{ prometheus_version }}"
    dest: "{{ prometheus_folder }}/current"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    state: link
  notify:
    - restart
  
