---
- name: Add necessary apt packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"

- name: Add GPG key for Docker
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add docker repository to apt sources (raspberry pi)
  apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
  when: "ansible_architecture == 'aarch64'"

- name: Add docker repository to apt sources (Ubuntu non-arch)
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
  when: "ansible_architecture == 'x86_64'"

- name: Update apt & install Docker
  apt:
    name: docker-ce
    update_cache: yes

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    group: docker
